global:
  scrape_interval: 15s
  evaluation_interval: 30s

rule_files:
  - /etc/prometheus/alerts/redis.rules.yml

scrape_configs:
  - job_name: redis-exporter
    static_configs:
      - targets:
          - redis-exporter:9121
  - job_name: celery-exporter
    static_configs:
      - targets:
          - celery-exporter:9808
