apiVersion: v1
kind: Namespace
metadata:
  name: trinity-production
  labels:
    name: trinity-production
    environment: production
    app: trinity
---
apiVersion: v1
kind: Namespace
metadata:
  name: trinity-staging
  labels:
    name: trinity-staging
    environment: staging
    app: trinity
---
