apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: trinity-fast-ssd
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: WaitForFirstConsumer
reclaimPolicy: Retain
allowVolumeExpansion: true
parameters:
  type: "ssd"
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: trinity-standard
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: WaitForFirstConsumer
reclaimPolicy: Retain
allowVolumeExpansion: true
parameters:
  type: "standard"
---
