apiVersion: v1
kind: Service
metadata:
  name: django-nodeport
  namespace: trinity-staging
spec:
  type: NodePort
  selector:
    app: django-staging
  ports:
  - port: 8000
    targetPort: 8000
    nodePort: 30080



